name: "Moobile"

exports: "moobile.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools for mobile devices"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

authors: "Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

sources:

  - "Source/Fx/Fx.Fold.js"
  - "Source/Translator/Translator.js"
  - "Source/Control/Exhibit.js"
  - "Source/Control/Exhibit.Image.js"
  - "Source/View/ScrollView.Gallery.js"
  - "Source/Util/Timer.js"
